# Set the mode for the plugin. This can either be "blacklist" or "whitelist".
#  blacklist: Versions listed below will not be allowed to connect.
#  whitelist: Only versions listed below will be allowed to connect.
mode = "blacklist"

# These versions MUST be the version number. You can check the numbers here: https://wiki.vg/Protocol_version_numbers
# By default, all versions from 1.7.2 to 1.21.10 are listed here.
# Everything here must have a comma after it!
versions = [
  4,
  5,
  47,
  107,
  108,
  109,
  110,
  210,
  315,
  316,
  335,
  338,
  340,
  393,
  401,
  404,
  477,
  480,
  485,
  490,
  498,
  573,
  575,
  578,
  735,
  736,
  751,
  753,
  754,
  755,
  756,
  757,
  758,
  759,
  760,
  761,
  762,
  763,
  764,
  765,
  766,
  767,
  768,
  769,
  770,
  771,
  772,
  773,
]

# Send this message when someone is denied access to the server.
# Use <versions> to show what versions your server uses. It will display like "1.8 - 1.16.3" or whatever.
# If you don't want to use <versions>, just remove it.
# You may need to change the default value if you use whitelist mode.
disconnect_message = "<red>The following version(s) are not allowed to join this server: <versions>."

# This will say "Player is connecting with protocol version" when someone joins.
# This is off by default to not spam your console, but you can enable it for debug reasons.
log_connection_versions = false

# No touch please :)
config_version = 6
